### ISSUE TITLE
Missing Class definition

### ISSUE THREAD

**Issue by jgonyea** [Ralla/grav-plugin-dotenv#2]
Hi,

I attempted to clone this repo to my plugins folder, but on a new page load, I receive the following error:
Class 'Dotenv\Dotenv' not found
at line 
\user\plugins\dotenv\dotenv.php:34

Am I missing steps for installing this?

**Comment by Ralla** [comment]
@jgonyea You probably need to run (in grav root): 

```bin/grav composer``` 

Since there's some requirements in https://github.com/Ralla/grav-plugin-dotenv/blob/master/composer.json

Let me know if that works, otherwise I will try to reproduce and update the readme.

**Comment by jgonyea** [comment]
Hi, I tried performing the `bin/grav composer` from the grav root, but it said there was nothing to install/ update.

**Comment by Ralla** [comment]
Try removing the entire plugin folder and reinstall with:

```bin/gpm install dotenv```

And perhaps run the composer command as well.

**Comment by jgonyea** [comment]
I tried that as well, with the same results.

**Comment by thekenshow** [comment]
I'm having the same issue on Grav 1.6.3. Would love to use this, but it blows up with Class 'Dotenv\Dotenv' not found, inside or outside the Admin.

**Comment by jgonyea** [comment]
Out of curiosity, @ralla, did you happen to add the dotenv to your grav site's composer file. That would make the plugin just "work"

**Comment by Ralla** [comment]
> Out of curiosity, @Ralla, did you happen to add the dotenv to your grav site's composer file. That would make the plugin just "work"

I might have yes. 

@thekenshow @jgonyea I have now added the vendor folder to the project, so try cloning the repo to your plugins folder or simply download the zip from here https://github.com/Ralla/grav-plugin-dotenv/releases/tag/1.0.1

gpm installation might now work yet, since the tag is now 1.0.1. 

Let me know if this works. And sorry for the late response!

**Comment by thekenshow** [comment]
Downloaded the 1.0.1 linked above and installed it. Created a .gravenv file with the suggested changes. No errors thrown now but the .gravenv settings (e.g., system.debugger.enabled=true) are having no effect. Also, the 1.0.1 CHANGELOG.md shows v1.0.0.

**Comment by Ralla** [comment]
@thekenshow this seems unrelated. Please create a new issue, and I'll look into it.

**Comment by thekenshow** [comment]
@Ralla Thanks, done: https://github.com/Ralla/grav-plugin-dotenv/issues/5
