### ISSUE TITLE
local / dev / prod Dotenv files

### ISSUE THREAD

**Issue by jnadaud** [Ralla/grav-plugin-dotenv#4]
Hi,

Consider using the Symfony component instead: https://github.com/symfony/symfony/tree/4.4/src/Symfony/Component/Dotenv

Like this we can have various .gravenv, ie: .gravenv, .gravenv.local, .gravenv.dev, etc.

Kind regards,

**Comment by Ralla** [comment]
Thanks, I'll look into it.
